### ISSUE TITLE
msfvenom: error when using --bad-chars

### ISSUE THREAD

**Issue by vipzen** [rapid7/metasploit-payloads#278]
Command: 

`$ msfvenom -p windows/meterpreter/reverse_tcp --platform win LHOST=192.168.1.55 LPORT=4444 -a x86 -f c -b '\x00\x0a\x0d'`

Result:
``` 
    /usr/local/bin/msfvenom:138:in `block in parse_args': uninitialized constant Rex (NameError)
	from /usr/local/Cellar/ruby@2.3/2.3.6_3/lib/ruby/2.3.0/optparse.rb:1578:in `block in parse_in_order'
	from /usr/local/Cellar/ruby@2.3/2.3.6_3/lib/ruby/2.3.0/optparse.rb:1534:in `catch'
	from /usr/local/Cellar/ruby@2.3/2.3.6_3/lib/ruby/2.3.0/optparse.rb:1534:in `parse_in_order'
	from /usr/local/Cellar/ruby@2.3/2.3.6_3/lib/ruby/2.3.0/optparse.rb:1528:in `order!'
	from /usr/local/Cellar/ruby@2.3/2.3.6_3/lib/ruby/2.3.0/optparse.rb:1620:in `permute!'
	from /usr/local/Cellar/ruby@2.3/2.3.6_3/lib/ruby/2.3.0/optparse.rb:1642:in `parse!'
	from /usr/local/bin/msfvenom:174:in `parse_args'
	from /usr/local/bin/msfvenom:287:in `<main>'
``` 

Without `-b` msfvenom runs without problem.

**Comment by wvu-r7** [comment]
Fixed in https://github.com/rapid7/metasploit-framework/pull/9765. Dupe of https://github.com/rapid7/metasploit-framework/issues/9763. This repo is for payloads only.
