### ISSUE TITLE
Session dies webcam_snap on MiAi Dual camera

### ISSUE THREAD

**Issue by MMLinuxer** [rapid7/metasploit-payloads#306]
hi 
I have a Xiaomi mi A1 phone with stock android 8.1 
the problem is that I get an error and the session dies when accessing the webcam
mi A1 has three cameras , front camera , back camera and back telephoto camera

I tested it on another samsung device (only two cameras ) and It worked correctly
I compiled the meterpreter apk payload into an android studio project and debug it 
(all required permissions are granted )
I got this error

`
W/System.err:     at com.metasploit.meterpreter.Channel$InteractThread.run(Unknown Source:6)
W/Thread-4: type=1400 audit(0.0:602): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=5429 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc: Access denied finding property "camera.hal1.packagelist"
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: google.com, PID: 12058
                  android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
                      at android.view.ViewRootImpl.setView(ViewRootImpl.java:769)
                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
                      at com.metasploit.meterpreter.android.webcam_start_android$1.run(webcam_start_android.java:82)
                      at android.os.Handler.handleCallback(Handler.java:790)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:172)
                      at android.app.ActivityThread.main(ActivityThread.java:6590)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
W/System.err: java.lang.RuntimeException: takePicture failed
W/System.err:     at android.hardware.Camera.native_takePicture(Native Method)
                  at android.hardware.Camera.takePicture(Camera.java:1599)
                  at android.hardware.Camera.takePicture(Camera.java:1540)
                  at com.metasploit.meterpreter.android.webcam_get_frame_android.execute(webcam_get_frame_android.java:34)
                  at com.metasploit.meterpreter.CommandManager.executeCommand(Unknown Source:14)
W/System.err:     at com.metasploit.meterpreter.TcpTransport.dispatch(Unknown Source:45)
                  at com.metasploit.meterpreter.Meterpreter.startExecuting(Unknown Source:32)
                  at com.metasploit.meterpreter.AndroidMeterpreter.<init>(AndroidMeterpreter.java:102)
                  at java.lang.reflect.Constructor.newInstance0(Native Method)
                  at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
W/System.err:     at androidpayload.stage.Meterpreter.start(Meterpreter.java:49)
                  at androidpayload.stage.Meterpreter.start(Meterpreter.java:21)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at google.com.Payload.readAndRunStage(Payload.java:131)
                  at google.com.Payload.runStagefromTCP(Payload.java:106)
                  at google.com.Payload.main(Payload.java:83)
W/System.err:     at google.com.Payload$1.run(Payload.java:53)
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'
`
=========================
`
W/System.err: Unknown request detected:
W/System.err: 	TLV_TYPE_METHOD = core_negotiate_tlv_encryption
W/System.err: 	TLV_TYPE_REQUEST_ID = 88122406053763816897080094277901
W/System.err: 	0x10226 = -----BEGIN PUBLIC KEY-----
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvCarNza2rOXgp9XSZhfu
              ZsAC80y59xiX6jxfILHkcf+sa1YzRh3MPRZ3nwPSZB0Y2BgLWepcR4cDw8xoj05+
              t+1IZQHQoONi+eU42xD3YTpLZtm3aIqhkHfcVEIwhQdC5+Fe/YrZWbB7Vo5H0RGO
              8nMPUtnQzfNl/tCa/8BS6vxEsDdXIKXqUA/sfGqC0FivlHU+ciBttvzsN98lC/MR
              0MVD8myCGQl1MK+byn2YS9wG2+7ux78xTHHSNIFxS1SDlQiKdGhWajoLOqwWsWWD
W/System.err: G0yzaNcr9jDFmZkXo2wKilw220RHcyULlqMVBGtMf0E6EHyfRCk4Heze/tzl8VLN
              7wIDAQAB
              -----END PUBLIC KEY-----
W/System.err: java.io.InterruptedIOException: read interrupted
W/System.err:     at libcore.io.Linux.readBytes(Native Method)
W/System.err:     at libcore.io.Linux.read(Linux.java:184)
                  at libcore.io.BlockGuardOs.read(BlockGuardOs.java:251)
W/System.err:     at libcore.io.IoBridge.read(IoBridge.java:528)
                  at java.io.FileInputStream.read(FileInputStream.java:254)
W/System.err:     at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
                  at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
W/System.err:     at java.io.FilterInputStream.read(FilterInputStream.java:107)
                  at com.metasploit.meterpreter.Channel$InteractThread.run(Unknown Source:6)
W/System.err: java.io.InterruptedIOException: read interrupted
W/System.err:     at libcore.io.Linux.readBytes(Native Method)
                  at libcore.io.Linux.read(Linux.java:184)
W/System.err:     at libcore.io.BlockGuardOs.read(BlockGuardOs.java:251)
                  at libcore.io.IoBridge.read(IoBridge.java:528)
W/System.err:     at java.io.FileInputStream.read(FileInputStream.java:254)
                  at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
W/System.err:     at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
                  at java.io.FilterInputStream.read(FilterInputStream.java:107)
W/System.err:     at com.metasploit.meterpreter.Channel$InteractThread.run(Unknown Source:6)
W/Thread-4: type=1400 audit(0.0:602): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=5429 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc: Access denied finding property "camera.hal1.packagelist"
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: google.com, PID: 12058
                  android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
                      at android.view.ViewRootImpl.setView(ViewRootImpl.java:769)
                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
                      at com.metasploit.meterpreter.android.webcam_start_android$1.run(webcam_start_android.java:82)
                      at android.os.Handler.handleCallback(Handler.java:790)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:172)
                      at android.app.ActivityThread.main(ActivityThread.java:6590)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
W/System.err: java.lang.RuntimeException: takePicture failed
W/System.err:     at android.hardware.Camera.native_takePicture(Native Method)
                  at android.hardware.Camera.takePicture(Camera.java:1599)
                  at android.hardware.Camera.takePicture(Camera.java:1540)
                  at com.metasploit.meterpreter.android.webcam_get_frame_android.execute(webcam_get_frame_android.java:34)
                  at com.metasploit.meterpreter.CommandManager.executeCommand(Unknown Source:14)
W/System.err:     at com.metasploit.meterpreter.TcpTransport.dispatch(Unknown Source:45)
                  at com.metasploit.meterpreter.Meterpreter.startExecuting(Unknown Source:32)
                  at com.metasploit.meterpreter.AndroidMeterpreter.<init>(AndroidMeterpreter.java:102)
                  at java.lang.reflect.Constructor.newInstance0(Native Method)
                  at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
W/System.err:     at androidpayload.stage.Meterpreter.start(Meterpreter.java:49)
                  at androidpayload.stage.Meterpreter.start(Meterpreter.java:21)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at google.com.Payload.readAndRunStage(Payload.java:131)
                  at google.com.Payload.runStagefromTCP(Payload.java:106)
                  at google.com.Payload.main(Payload.java:83)
W/System.err:     at google.com.Payload$1.run(Payload.java:53)
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'

`

**Comment by timwr** [comment]
I suspect this may be because we're using the old long deprecated Camera APIs.
https://github.com/rapid7/metasploit-payloads/blob/master/java/androidpayload/library/src/com/metasploit/meterpreter/android/webcam_start_android.java#L31
e.g `https://developer.android.com/reference/android/hardware/Camera` vs `https://developer.android.com/reference/android/hardware/camera2/CameraManager`

Alternatively it could also because we use a bit of a hack to create the preview surface (a 1x1 invisible toast pixel): https://github.com/rapid7/metasploit-payloads/blob/master/java/androidpayload/library/src/com/metasploit/meterpreter/android/webcam_start_android.java#L77

I honestly didn't expect webcam_snap to work this long on so many future versions of Android, especially while the screen is off.

**Comment by MMLinuxer** [comment]
yeah maybe because of that ,
actually I'm using android studio sdk 28 to compile the stager
getting android studio to work with sdk 22 gave me headache , but after I got it to work , I upgraded to android studio 3.1 and everything messed up again 
I didn't have the chance to recompile the stager to sdk 22  and test it 

I also remember that I had some issues  with the camera in the past , I was testing the android meterpreter on one of my friends' phone (with his consent) , It had dual cameras , the first was normal but the second was a monochrome view, when I tried to snap a picture  , the photo came out messed up  , It actually snapped from the monochrome camera not the main camera. so clearly there is an issue with webcam snap in the main payload as you said . 

are you planning to upgrade the android meterpreter and fix these issues or you will just leave it as it is ? 
android is developing and It's putting more and more obstacles against malwares 
especially android 8 and above 
I think it's getting more and more closer to be as restricted as IOS . and eventually manufacturers may even prohibit installing apks at all not just display a warning  , apps will be installed only from the store , like IOS.

I did some researches and analysed  some android malwares to know how they works , I found  RAT called spynote , there is a free version , but It's clearly not FUD at all and too hard to encrypt , the FUD version costs an astronomically 500 USD and 4000 If they're going (some how) to host your app on google play .
It's built using SDK 22 since it asks for permission on installing .
the thing worked very well on android 8.1 , and It was very persistent , the session never dies even with all the restrictions the system is putting on it . you may want to decompile the client and see how It works , I actually did that using jadx ,( although I got errors and couldn't decompile  some classes ),
It had a service working on foreground which is very suspicious for the victim , but you have the choice to disable that  , still the service will remain working and restart if it got killed ,
It uses a simple alarm manager to trigger the service every time the system kills it , however , I know by experience that android O may kill your app and never trigger the alarm manager in certain occasions , but spynote is still working for two weeks on my phone until now , 
I know It's not using a Job Intent Service because the client asks for permissions on installing which means that it's coded with an sdk lower than 23 . I couldn't figure out how spynote is still working all this long on android 8 .
It had a cpu partial wakelock so that it can bypass doze mode when the screen is closed (meterpreter has this too)
It has  no 'disable battery optimization ' option , so when you activate power saver , spynote dies immediately , but restarts when deactivating the power saver . by the way , I tried to disable power optimization for meterpreter on android 8 and I managed to get an active session for almost 3 days ! 
 also if you want to test the stager to see how persistent it is , I suggest doing this on a real phone as the emulator is always plugged into power by default so the system won't kill any service at all,
and take in mind that most manufacturers customize the system and add their own powermanager and even sometimes modify the garbage collector  , so there are  many chances that the service might get killed

I hope what I said might help a little , thank you .
