### ISSUE TITLE
Python Meterpreter - Too many open files - Not removing process pipes

### ISSUE THREAD

**Issue by sjanusz-r7** [rapid7/metasploit-payloads#569]
The Python Meterpreter seems to raise `Too many open files` error. This results in us not being able to run any more tests or `cmd_exec` calls etc.

## Steps to reproduce

1. Get a Python Meterpreter session with `MeterpreterDebugBuild true`
2. `loadpath test/modules`
3. `use test/meterpreter`
4. `repeat -n 30 'run session=-1'` (this could be adjusted depending on your `ulimit`)
5. Confirm that the tests start failing with an error similar to `Too many files opened`.
6. `lsof -p {process_id_of_our_python_shell_here}` and confirm that there are a _huge_ number of pipes opened.

## Were you following a specific guide/tutorial or reading documentation?

No.

## Expected behavior

Python Meterpreter shouldn't be leaking process pipes

## Current behavior

We get the following error logs:

```
DEBUG:root:Traceback (most recent call last):
  File "<string>", line 1736, in create_response
  File "ext_server_stdapi.py", line 1193, in stdapi_sys_process_execute
  File "<string>", line 838, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 928, in _execute_child
    errpipe_read, errpipe_write = self.pipe_cloexec()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 865, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files
```

And the following open pipes with `lsof -p {pid_here}`:

```
Python  38688 sjanusz    0u   CHR               16,6 0t1777721                2137 /dev/ttys006
Python  38688 sjanusz    1u   CHR               16,6 0t1777721                2137 /dev/ttys006
Python  38688 sjanusz    2u   CHR               16,6 0t1777721                2137 /dev/ttys006
Python  38688 sjanusz    3u  IPv4 0xd7d773d90a42cacf       0t0                 TCP localhost:50990->localhost:krb524 (ESTABLISHED)
Python  38688 sjanusz    5   PIPE 0x93a6c0294ba29423     16384
Python  38688 sjanusz    6u   CHR               16,6 0t1777721                2137 /dev/ttys006
Python  38688 sjanusz    7   PIPE 0x78a95b49e72ecc35     16384
Python  38688 sjanusz    8   PIPE 0x9f85a1fb9bc38acb     16384
Python  38688 sjanusz    9   PIPE 0x3ec6bb810a7638ef     16384
Python  38688 sjanusz   10   PIPE 0xa63212cac94ab58a     16384
Python  38688 sjanusz   11   PIPE 0xea4a25fbcdbb4c0b     16384
Python  38688 sjanusz   12   PIPE 0x8faf60659d37084e     16384
Python  38688 sjanusz   13   PIPE 0xfa796a2db1a7b1ae     16384
Python  38688 sjanusz   14r   CHR               17,1   0t12200                 593 /dev/urandom
Python  38688 sjanusz   15   PIPE 0x920f11de80af9079     16384
Python  38688 sjanusz   16   PIPE 0x7034892b08cc72ca     16384
Python  38688 sjanusz   17   PIPE  0x8f944d5da9e56c7     16384
Python  38688 sjanusz   18   PIPE 0xeb0340e14a737386     16384
Python  38688 sjanusz   19   PIPE 0x7d2780cbc59a2232     16384
Python  38688 sjanusz   20   PIPE  0xd6cb56ea0ab6a8d     16384
Python  38688 sjanusz   21   PIPE 0xc0008990734a419a     16384
...
...
Python  38688 sjanusz  245   PIPE 0x6e934edf67b76c73     16384
Python  38688 sjanusz  246   PIPE 0xab7e795771b6caea     16384
Python  38688 sjanusz  247   PIPE 0x9d93c2e3080bc243     16384
Python  38688 sjanusz  248   PIPE 0x1df1246e125da84c     16384
Python  38688 sjanusz  250   PIPE 0x15a6b3bf2a299ffb     16384
```

`ulimit -a` (although the limit here is quite low, Meterpreter should manage the pipes better):
```
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2784
-n: file descriptors                256
```

`ls -p {pid}`:
```
lsof -p 38688 | wc -l
     283
```

### Metasploit version

```
Framework: 6.1.41-dev-73ac1d1422
Console  : 6.1.41-dev-73ac1d1422
```

**Comment by adfoster-r7** [comment]
I believe this is fixed now; by https://github.com/rapid7/metasploit-payloads/pull/570 and https://github.com/rapid7/metasploit-payloads/pull/653 - and potentially others
